services:
  - type: web
    name: bms-backend
    env: docker
    dockerfilePath: ./Dockerfile.backend
    dockerContext: .
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        value: YOUR_DATABASE_URL_HERE
      - key: PORT
        value: 5000

  - type: static_site
    name: bms-frontend
    plan: free
    rootDir: bms-frontend-ts
    buildCommand: npm install && npm run build
    publishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
