services:
  - type: web
    name: bms-backend
    env: docker
    dockerfilePath: ./Dockerfile.backend
    dockerContext: .
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        value: mongodb+srv://chandukampasati1_db_user:1FNeTyxyz0mEgLbb@cluster0.xns4imt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: PORT
        value: 5000

  - type: web
    name: bms-frontend
    env: docker
    dockerfilePath: ./Dockerfile.frontend
    dockerContext: .
    plan: free
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
